# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, choices=[(b'email', 'by email'), (b'fax', 'by fax')], max_length=20)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confrontiv.Inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry Request',
                'verbose_name_plural': 'Inquiry Requests',
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('response_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Inquiry Response',
                'verbose_name_plural': 'Inquiry Responses',
            },
        ),
        migrations.CreateModel(
            name='InquiryTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Inquiry Template',
                'verbose_name_plural': 'Inquiry Templates',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='RecipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Recipient Group',
                'verbose_name_plural': 'Recipient Groups',
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='groups',
            field=models.ManyToManyField(to='confrontiv.RecipientGroup'),
        ),
        migrations.AddField(
            model_name='inquiryresponse',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confrontiv.Recipient'),
        ),
        migrations.AddField(
            model_name='inquiryresponse',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confrontiv.InquiryRequest'),
        ),
        migrations.AddField(
            model_name='inquiryrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confrontiv.Recipient'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='confrontiv.RecipientGroup'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='confrontiv.InquiryTemplate'),
        ),
    ]
