# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confrontiv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquirytemplate',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
