# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confrontiv', '0002_auto_20170222_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryrequest',
            name='has_response',
            field=models.BooleanField(default=False),
        ),
    ]
